[2024-11-01T14:11:44.296+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: updating_stock_data.reformating_datas manual__2024-11-01T13:34:11.696229+00:00 [queued]>
[2024-11-01T14:11:44.305+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: updating_stock_data.reformating_datas manual__2024-11-01T13:34:11.696229+00:00 [queued]>
[2024-11-01T14:11:44.306+0000] {taskinstance.py:2193} INFO - Starting attempt 6 of 7
[2024-11-01T14:11:44.317+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): reformating_datas> on 2024-11-01 13:34:11.696229+00:00
[2024-11-01T14:11:44.322+0000] {standard_task_runner.py:60} INFO - Started process 1199 to run task
[2024-11-01T14:11:44.325+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'updating_stock_data', 'reformating_datas', 'manual__2024-11-01T13:34:11.696229+00:00', '--job-id', '176', '--raw', '--subdir', 'DAGS_FOLDER/polars_postgres.py', '--cfg-path', '/tmp/tmpg28oelj2']
[2024-11-01T14:11:44.326+0000] {standard_task_runner.py:88} INFO - Job 176: Subtask reformating_datas
[2024-11-01T14:11:44.372+0000] {task_command.py:423} INFO - Running <TaskInstance: updating_stock_data.reformating_datas manual__2024-11-01T13:34:11.696229+00:00 [running]> on host 07e6c451f8a5
[2024-11-01T14:11:44.445+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow_development' AIRFLOW_CTX_DAG_ID='updating_stock_data' AIRFLOW_CTX_TASK_ID='reformating_datas' AIRFLOW_CTX_EXECUTION_DATE='2024-11-01T13:34:11.696229+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-01T13:34:11.696229+00:00'
[2024-11-01T14:11:44.446+0000] {logging_mixin.py:188} INFO - Error in data reformatting: No valid data found in the API response.
[2024-11-01T14:11:44.447+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/polars_postgres.py", line 53, in reformating_datas
    raise ValueError("No valid data found in the API response.")
ValueError: No valid data found in the API response.
[2024-11-01T14:11:44.458+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=updating_stock_data, task_id=reformating_datas, execution_date=20241101T133411, start_date=20241101T141144, end_date=20241101T141144
[2024-11-01T14:11:44.469+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 176 for task reformating_datas (No valid data found in the API response.; 1199)
[2024-11-01T14:11:44.498+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-01T14:11:44.521+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
