[2024-11-01T14:24:15.032+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: updating_stock_data.reformating_datas scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-11-01T14:24:15.044+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: updating_stock_data.reformating_datas scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-11-01T14:24:15.045+0000] {taskinstance.py:2193} INFO - Starting attempt 11 of 11
[2024-11-01T14:24:15.069+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): reformating_datas> on 2024-09-30 00:00:00+00:00
[2024-11-01T14:24:15.074+0000] {standard_task_runner.py:60} INFO - Started process 1695 to run task
[2024-11-01T14:24:15.077+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'updating_stock_data', 'reformating_datas', 'scheduled__2024-09-30T00:00:00+00:00', '--job-id', '195', '--raw', '--subdir', 'DAGS_FOLDER/polars_postgres.py', '--cfg-path', '/tmp/tmpvrw2_2ng']
[2024-11-01T14:24:15.079+0000] {standard_task_runner.py:88} INFO - Job 195: Subtask reformating_datas
[2024-11-01T14:24:15.132+0000] {task_command.py:423} INFO - Running <TaskInstance: updating_stock_data.reformating_datas scheduled__2024-09-30T00:00:00+00:00 [running]> on host 07e6c451f8a5
[2024-11-01T14:24:15.351+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow_development' AIRFLOW_CTX_DAG_ID='updating_stock_data' AIRFLOW_CTX_TASK_ID='reformating_datas' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T00:00:00+00:00'
[2024-11-01T14:24:15.353+0000] {logging_mixin.py:188} INFO - Error in data reformatting: '1. open'
[2024-11-01T14:24:15.354+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/polars_postgres.py", line 46, in reformating_datas
    data = [{
  File "/opt/airflow/dags/polars_postgres.py", line 48, in <listcomp>
    'Open': q['1. open'],
KeyError: '1. open'
[2024-11-01T14:24:15.365+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=updating_stock_data, task_id=reformating_datas, execution_date=20240930T000000, start_date=20241101T142415, end_date=20241101T142415
[2024-11-01T14:24:15.377+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 195 for task reformating_datas ('1. open'; 1695)
[2024-11-01T14:24:15.410+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-01T14:24:15.436+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
