[2024-11-01T13:49:03.518+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: updating_stock_data.reformating_datas scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-11-01T13:49:03.529+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: updating_stock_data.reformating_datas scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-11-01T13:49:03.530+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-11-01T13:49:03.547+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): reformating_datas> on 2024-09-30 00:00:00+00:00
[2024-11-01T13:49:03.553+0000] {standard_task_runner.py:60} INFO - Started process 336 to run task
[2024-11-01T13:49:03.557+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'updating_stock_data', 'reformating_datas', 'scheduled__2024-09-30T00:00:00+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/polars_postgres.py', '--cfg-path', '/tmp/tmptv3c1z__']
[2024-11-01T13:49:03.558+0000] {standard_task_runner.py:88} INFO - Job 154: Subtask reformating_datas
[2024-11-01T13:49:03.635+0000] {task_command.py:423} INFO - Running <TaskInstance: updating_stock_data.reformating_datas scheduled__2024-09-30T00:00:00+00:00 [running]> on host 07e6c451f8a5
[2024-11-01T13:49:03.724+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow_development' AIRFLOW_CTX_DAG_ID='updating_stock_data' AIRFLOW_CTX_TASK_ID='reformating_datas' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T00:00:00+00:00'
[2024-11-01T13:49:03.729+0000] {logging_mixin.py:188} INFO - Error in data reformatting: unable to find column "Date"; valid columns: []
[2024-11-01T13:49:03.729+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/polars_postgres.py", line 51, in reformating_datas
    if result.collect().shape[0] == 0:
  File "/home/airflow/.local/lib/python3.8/site-packages/polars/lazyframe/frame.py", line 2053, in collect
    return wrap_df(ldf.collect(callback))
polars.exceptions.ColumnNotFoundError: unable to find column "Date"; valid columns: []
[2024-11-01T13:49:03.743+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=updating_stock_data, task_id=reformating_datas, execution_date=20240930T000000, start_date=20241101T134903, end_date=20241101T134903
[2024-11-01T13:49:03.755+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 154 for task reformating_datas (unable to find column "Date"; valid columns: []; 336)
[2024-11-01T13:49:03.769+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-01T13:49:03.797+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
